### ISSUE TITLE
Save/Load button missing various HELM formats

### ISSUE THREAD

**Issue by TianhongZhang** [tony-yuan/JsHELM#58] opened 2016-10-12 20:04 UTC
Currently, it has the default small molecule options, but not the biomolecule options such as HELM, xHELM.

**Comment by ClairePA** [comment] 2016-10-25 15:05
I see the biomolecule formats in the canvas save/load dialogue box. Which one are you looking at?

**Comment by TianhongZhang** [comment] 2016-10-28 12:07
I can see the 'HELM' and 'xHELM' are save/load options now and was able to save files. 
A few issues:
1. We have the Save/Load label on the buttons, but we use Export/Import in the popup dialogs, and should change them to Save/Load for consistency.
2. Still unable to load files due to CORS issue. My web app and helm service running on different servers. The complaint is from the web app server, not the service server.
3. a default file name is provided for Save option, which is nice, but the user does not have an option to change it.

**Comment by ClairePA** [comment] 2016-10-28 15:58
MS Edge gives the option to 'Save as', but Chrome does not, however it provides a new name if the file exists. Comment 3 is acceptable as it works now.

**Comment by tony-yuan** [comment] 2016-10-31 23:04
#1 is fixed in 2016-10-31 update

**Comment by ClairePA** [comment] 2016-11-01 13:38
Clicking the save and load buttons now does nothing at all for me. I can't save or load anything.

**Comment by tony-yuan** [comment] 2016-11-03 17:54
I cannot reproduce it with Chrome and Edge.  You might need refresh the browser page.

**Comment by ClairePA** [comment] 2016-11-04 10:45
Confirmed OK now. Must have been a glitch on my machine.

**Closed by ClairePA** 2016-11-04 10:45 UTC
